version: '3.8'

services:
  mcp-postgres:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - type: bind
        source: ./postgres/init.sh
        target: /docker-entrypoint-initdb.d/init.sh
        read_only: true
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  connector-service:
    build: ./connector-service
    env_file: .env
    environment:
      DB_HOST: mcp-postgres
    ports:
      - "8000:8000"
    depends_on:
      mcp-postgres:
        condition: service_healthy
    networks:
      - mcp-network

volumes:
  postgres_data:

networks:
  mcp-network: